# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(711, 473)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Iguane.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(1.0)
        Form.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.launch = QtWidgets.QPushButton(self.tab)
        self.launch.setObjectName("launch")
        self.verticalLayout_3.addWidget(self.launch)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph = QtWidgets.QListWidget(self.tab)
        self.graph.setObjectName("graph")
        self.horizontalLayout.addWidget(self.graph)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.load = QtWidgets.QPushButton(self.tab)
        self.load.setObjectName("load")
        self.verticalLayout_5.addWidget(self.load)
        self.display = QtWidgets.QPushButton(self.tab)
        self.display.setEnabled(True)
        self.display.setObjectName("display")
        self.verticalLayout_5.addWidget(self.display)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graph_2 = QtWidgets.QListWidget(self.tab_2)
        self.graph_2.setObjectName("graph_2")
        self.horizontalLayout_2.addWidget(self.graph_2)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.load_2 = QtWidgets.QPushButton(self.tab_2)
        self.load_2.setObjectName("load_2")
        self.verticalLayout_13.addWidget(self.load_2)
        self.reduc = QtWidgets.QPushButton(self.tab_2)
        self.reduc.setEnabled(True)
        self.reduc.setObjectName("reduc")
        self.verticalLayout_13.addWidget(self.reduc)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.time = QtWidgets.QSpinBox(self.tab_3)
        self.time.setMaximum(86400)
        self.time.setObjectName("time")
        self.horizontalLayout_3.addWidget(self.time)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.graph_3 = QtWidgets.QListWidget(self.tab_3)
        self.graph_3.setObjectName("graph_3")
        self.horizontalLayout_4.addWidget(self.graph_3)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.load_3 = QtWidgets.QPushButton(self.tab_3)
        self.load_3.setObjectName("load_3")
        self.verticalLayout_15.addWidget(self.load_3)
        self.color = QtWidgets.QPushButton(self.tab_3)
        self.color.setEnabled(True)
        self.color.setObjectName("color")
        self.verticalLayout_15.addWidget(self.color)
        self.color_1 = QtWidgets.QPushButton(self.tab_3)
        self.color_1.setObjectName("color_1")
        self.verticalLayout_15.addWidget(self.color_1)
        self.nCompo = QtWidgets.QPushButton(self.tab_3)
        self.nCompo.setObjectName("nCompo")
        self.verticalLayout_15.addWidget(self.nCompo)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_14.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.matrice = QtWidgets.QLabel(self.tab_5)
        self.matrice.setMinimumSize(QtCore.QSize(120, 0))
        self.matrice.setMaximumSize(QtCore.QSize(16777215, 20))
        self.matrice.setText("")
        self.matrice.setObjectName("matrice")
        self.gridLayout.addWidget(self.matrice, 8, 3, 1, 1)
        self.precision = QtWidgets.QLabel(self.tab_5)
        self.precision.setMaximumSize(QtCore.QSize(16777215, 20))
        self.precision.setText("")
        self.precision.setObjectName("precision")
        self.gridLayout.addWidget(self.precision, 7, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 4)
        self.nomFichier = QtWidgets.QListWidget(self.tab_5)
        self.nomFichier.setMaximumSize(QtCore.QSize(16777215, 20))
        self.nomFichier.setObjectName("nomFichier")
        self.gridLayout.addWidget(self.nomFichier, 1, 0, 1, 1)
        self.fichier = QtWidgets.QLabel(self.tab_5)
        self.fichier.setText("")
        self.fichier.setObjectName("fichier")
        self.gridLayout.addWidget(self.fichier, 6, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 2, 1, 1)
        self.chercheFichier = QtWidgets.QPushButton(self.tab_5)
        self.chercheFichier.setMaximumSize(QtCore.QSize(30, 20))
        self.chercheFichier.setObjectName("chercheFichier")
        self.gridLayout.addWidget(self.chercheFichier, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setMaximumSize(QtCore.QSize(55, 20))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 2, 1, 1)
        self.train = QtWidgets.QPushButton(self.tab_5)
        self.train.setMaximumSize(QtCore.QSize(70, 22))
        self.train.setObjectName("train")
        self.gridLayout.addWidget(self.train, 2, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tab_5)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 220))
        self.listWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 5, 0, 4, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setMaximumSize(QtCore.QSize(35, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 4)
        self.spinBox = QtWidgets.QSpinBox(self.tab_5)
        self.spinBox.setMaximumSize(QtCore.QSize(50, 20))
        self.spinBox.setMaximum(1000)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setMaximumSize(QtCore.QSize(70, 22))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.test = QtWidgets.QPushButton(self.tab_5)
        self.test.setMaximumSize(QtCore.QSize(16777215, 22))
        self.test.setObjectName("test")
        self.gridLayout.addWidget(self.test, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Iguane"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'trebuchet MS,sans-serif\'; font-size:15px; font-variant:small-caps;\">Affichage de graphe grâce à Cytoscape</span></p></body></html>"))
        self.launch.setText(_translate("Form", "Lancer Cytoscape"))
        self.load.setText(_translate("Form", "Charger un graphe"))
        self.display.setText(_translate("Form", "Afficher le graphe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Affichage de graphe"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'trebuchet MS,sans-serif\'; font-size:15px; font-variant:small-caps;\">Réduction de graphes</span></p></body></html>"))
        self.load_2.setText(_translate("Form", "Charger un graphe"))
        self.reduc.setText(_translate("Form", "Réduire le graphe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Réduction d\'un graphe"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'trebuchet MS,sans-serif\'; font-size:15px; font-variant:small-caps;\">Coloration du graphe réduit grâce à IGGY-poc</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><body><p align=\"center\">Temps d\'exécution maximal (en secondes) :</p></body></html>"))
        self.load_3.setText(_translate("Form", "Charger un graphe"))
        self.color.setText(_translate("Form", "Identifier les colorations"))
        self.color_1.setText(_translate("Form", "Colorer le graphe"))
        self.nCompo.setText(_translate("Form", "N Composantes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Coloration d\'un graphe"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'trebuchet MS,sans-serif\'; font-size:15px; font-variant:small-caps;\">Calcul de similarité</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Calcul de similarité"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'trebuchet MS,sans-serif\'; font-size:15px; font-variant:small-caps;\">Création du classificateur</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\">Matrice de confusion :</p></body></html>"))
        self.chercheFichier.setText(_translate("Form", "..."))
        self.label_10.setText(_translate("Form", "<html><head/><body><p>Précision :</p></body></html>"))
        self.train.setText(_translate("Form", "Train"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\">Nombre d\'arbres :</p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'trebuchet MS,sans-serif\'; font-size:15px; font-variant:small-caps;\">Module de test</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Charger"))
        self.test.setText(_translate("Form", "Test"))
        self.label_7.setText(_translate("Form", "Fichier testé :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Classificateur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

